name:                sudoku-solver-haskell
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- text
- containers
- recursion-schemes  

default-extensions:
- OverloadedStrings

ghc-options:
  - -Wall
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wunused-packages

library:
  source-dirs: src

executables:
  sudoku-solver-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sudoku-solver-haskell

tests:
  sudoku-solver-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sudoku-solver-haskell
    - hspec
    - hspec-discover
    - QuickCheck


verbatim:
  cabal-version: 3.0
